// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Use DIRECT_URL (session pooler, port 5432) for migrations locally.
// Fall back to DATABASE_URL when DIRECT_URL is not set (e.g. on Vercel during
// `prisma generate` — no direct connection is needed for code generation).
const datasourceUrl =
  process.env.DIRECT_URL ?? process.env.DATABASE_URL ?? "";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: datasourceUrl,
  },
});
